### ISSUE TITLE
GPS position formatting error

### ISSUE THREAD

**Issue by lkarsten** [lkarsten/fdxread#1]
Reported by @first317 on slack.

```
$GPGLL,546.144,N,1048.4669,E,183425,A,,*15
$GPGLL,546.144,N,1048.4669,E,183426,A,,*16
$GPRMC,183427,A,546.144,N,1048.4669,E,0.04,269.65,070117,0.0,E,*6D
$GPHDT,269.65,T,*27
$GPGLL,546.144,N,1048.4669,E,183427,A,,*17
```

which decodes to (with https://rl.se/gprmc )

> Position	5.769067°N 10.807782°E
> Timestamp	Sat, 7 Jan 2017 18:34:27 UTC
> Close to	Foumban, Cameroon
> Local time	Sat, 7 Jan 2017 19:34:27 WAT
> Timezone	Africa/Douala (UTC +0100)
> 

Expected: (i think) somewhere in Germany.

**Comment by ProfAronnax** [comment]
Hey Lasse,
yes it should be somewhere in north Germany. 

Correct Position should be 54° 61.44’N 10° 48,46’E
It seems that the fault is a shifting digit from degrees to minute 

I think i have to sail ca 300Nm with course north to come in your Sailing area :-)

**Comment by lkarsten** [comment]
I think 352df6b22c1d8cc5ea96601f5fe541a1bf2e4871 fixed this, but I need the original failing input to validate. Can you take a look, @leifnagtegaal ?

**Comment by ProfAronnax** [comment]
[serialdump.fdx.txt](https://github.com/lkarsten/GND10read/files/702648/serialdump.fdx.txt)
i pulled your last commit in your rep, but i am still in Cameroon

**Comment by lkarsten** [comment]
Hi. Thanks for the sample data.

I've added another patch now, which puts you firmly in Germany at least in my testing. If you have the time, further testing would be very much welcome. @leifnagtegaal

**Comment by ProfAronnax** [comment]
Jippieh, now is my position fix correct

**Comment by lkarsten** [comment]
@leifnagtegaal thanks! :-)

**Comment by lkarsten** [comment]
Note: 595a485 should have referenced #2, not this one.
