### ISSUE TITLE
Q: gWind Wireless 2 Transducer

### ISSUE THREAD

**Issue by rkapsi** [lkarsten/fdxread#11]
Hello,

this is a long shot but I'm wondering if you have any information about the gWind Wireless 2 Transducer's protocol and how open or closed it is? It's supposedly using ANT for signaling and I'm looking to replicate something along the lines of a GNX Wind Instrument on an Android device. Wouldn't want to spend the money on the gWind if it's hopeless.

Thanks!

**Comment by lkarsten** [comment]
Hi. I don't have any information on that, I'm afraid.

**Comment by rkapsi** [comment]
Thanks!
